services:
  - type: web
    name: supertokens-core
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: "./gradlew assemble"
    startCommand: "java -Djava.security.egd=file:/dev/urandom -classpath ./core/*:./plugin-interface/* io.supertokens.Main ./"
    envVars:
      - key: SUPERTOKENS_HOST
        value: 0.0.0.0
      - key: SUPERTOKENS_PORT
        value: 3567
